create sequence audit_trail_seq start with 1 increment by  1;
create sequence catalog_item_attribute_seq start with 1 increment by  1;
create sequence catalog_item_price_seq start with 1 increment by  1;
create sequence catalog_item_seq start with 1 increment by  1;
create sequence catalog_seq start with 1 increment by  1;
create sequence company_address_id_seq start with 1 increment by  1;
create sequence company_change_log_seq start with 1 increment by  1;
create sequence company_seq start with 1 increment by  1;
create sequence eclass_code_lkup_id_seq start with 1 increment by  1;
create sequence fail_code_seq start with 1 increment by  1;
create sequence gtin_id_seq start with 1 increment by  1;
create sequence hibc_id_seq start with 1 increment by  1;
create sequence import_transaction_id_seq start with 1 increment by  1;
create sequence item_asset_seq start with 1 increment by  1;
create sequence item_attribute_seq start with 1 increment by  1;
create sequence item_barcode_seq start with 1 increment by  1;
create sequence item_change_log_seq start with 1 increment by  1;
create sequence item_seq start with 1 increment by  1;
create sequence item_taxonomy_seq start with 1 increment by  1;
create sequence organisation_seq start with 1 increment by  1;
create sequence sic_code_lkup_seq start with 1 increment by  1;
create sequence substitute_item_seq start with 1 increment by  1;
create sequence tax_types_seq start with 1 increment by  1;
create sequence triage_action_seq start with 1 increment by  1;
create sequence triage_seq start with 1 increment by  1;
create sequence unspsc_code_lkup_seq start with 1 increment by  1;
create sequence uom_lookup_seq start with 1 increment by  1;
create sequence user_seq start with 1 increment by  1;
create table audit_trail (id number(19,0) not null, comments varchar2(255 char), date_row_added timestamp not null, display_text varchar2(4000 char), document_no varchar2(255 char) not null, status_addtl_info varchar2(100 char), status_id number(19,0) not null, fail_code_id number(19,0), primary key (id));
create table auth (auth_name varchar2(50 char) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, primary key (auth_name));
create table catalog (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar2(255 char), key varchar2(50 char), name varchar2(50 char), site varchar2(50 char), type varchar2(10 char), version number(10,0), company_id number(19,0), organisation_id number(19,0), parent_catalog_id number(19,0), primary key (id));
create table catalog_child_item (catalog_id number(19,0) not null, catalog_item_id number(19,0) not null, primary key (catalog_id, catalog_item_id));
create table catalog_item (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar2(255 char), expense_code varchar2(10 char) not null, hcted varchar2(10 char) not null, item_band varchar2(10 char), name varchar2(50 char), pending_from varchar2(10 char) not null, preferred_item_order varchar2(10 char), supplier_part_no varchar2(100 char), type varchar2(10 char), uom_qty number(19,0), validated varchar2(1 char) not null, item_id number(19,0), substitute_item_id number(19,0) not null, primary key (id));
create table catalog_item_attribute (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, key varchar2(50 char), value varchar2(255 char), catalog_item_id number(19,0), primary key (id));
create table catalog_item_price (id number(19,0) not null, active_flag varchar2(1 char) not null, currency varchar2(3 char), date_row_added timestamp not null, date_row_updated timestamp not null, lead_time varchar2(50 char), net_amount number(10,4) not null, max_order_qty number(10,0), min_order_qty number(10,0), price_break_max_qty number(10,0), price_break_min_qty number(10,0), price_break_style number(10,0), price_type varchar2(16 char), tax varchar2(50 char), valid_from timestamp, valid_to timestamp, catalog_item_id number(19,0), primary key (id));
create table company (id number(19,0) not null, active_flag varchar2(1 char) not null, companies_house_no varchar2(100 char), company_name varchar2(100 char), date_row_added timestamp not null, date_row_updated timestamp not null, duns_no varchar2(100 char), nuts_code varchar2(10 char), refresh varchar2(1 char) not null, status varchar2(20 char), address_id number(19,0), sic_code_id number(19,0), primary key (id));
create table company_address (id number(19,0) not null, active_flag varchar2(1 char) not null, address_name varchar2(50 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, gln varchar2(15 char) not null, line1 varchar2(255 char), line2 varchar2(255 char), line3 varchar2(255 char), nuts_code varchar2(10 char), postal_code varchar2(10 char), primary key (id));
create table company_change_log (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, information varchar2(500 char), type varchar2(10 char), company_id number(19,0), import_id number(19,0), primary key (id));
create table eclass_codes_lkup (eclass_code_lkup_id number(19,0) not null, active_flag varchar2(1 char) not null, code varchar2(10 char), date_row_added timestamp not null, date_row_updated timestamp not null, description varchar2(255 char), description_msg_key varchar2(255 char), primary key (eclass_code_lkup_id));
create table fail_code (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar2(50 char), name varchar2(50 char), text varchar2(100 char), primary key (id));
create table gtin (id number(19,0) not null, active_flag varchar2(1 char) not null, barcode_validation_id number(19,0), date_row_added timestamp not null, date_row_updated timestamp not null, gtin number(19,0) not null, text varchar2(14 char) not null, type varchar2(50 char) not null, import_transaction_id number(19,0), primary key (id));
create table hibc (id number(19,0) not null, active_flag varchar2(1 char) not null, barcode_validation_id number(19,0), date_row_added timestamp not null, date_row_updated timestamp not null, hibc varchar2(50 char) not null, import_transaction_id number(19,0), primary key (id));
create table import_transactions (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar2(500 char), primary key (id));
create table item (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar2(255 char), gs1_gpc_code number(19,0), long_description varchar2(500 char), msrp float, name varchar2(100 char), replacement_mfgr_no varchar2(100 char), synonyms varchar2(500 char), type varchar2(10 char), uom varchar2(10 char), primary key (id));
create table item_asset (id number(19,0) not null, active_flag varchar2(1 char) not null, type varchar2(10 char), date_row_added timestamp not null, date_row_updated timestamp not null, resource_location varchar2(500 char), item_id number(19,0), primary key (id));
create table item_attribute (id number(19,0) not null, active_flag varchar2(1 char) not null, attribute_id varchar2(10 char), date_row_added timestamp not null, date_row_updated timestamp not null, key varchar2(50 char), type varchar2(10 char), value varchar2(255 char), item_id number(19,0), primary key (id));
create table item_barcode (id number(19,0) not null, active_flag varchar2(1 char) not null, code varchar2(20 char), code_int number(19,0), code_string varchar2(10 char), date_row_added timestamp not null, date_row_updated timestamp not null, type varchar2(10 char), item_id number(19,0) not null, parent_item_barcode_id number(19,0), primary key (id));
create table item_change_log (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, information varchar2(500 char), type varchar2(10 char), item_id number(19,0), primary key (id));
create table item_taxonomy (id number(19,0) not null, active_flag varchar2(1 char) not null, asset_type varchar2(10 char), date_row_added timestamp not null, date_row_updated timestamp not null, resource_location varchar2(500 char), item_id number(19,0) not null, primary key (id));
create table organisation (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, primary key (id));
create table sic_codes_lkup (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar2(255 char), description_msg_key varchar2(255 char), sic_code varchar2(50 char), primary key (id));
create table substitute_item (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, supplier_part_no varchar2(50 char), primary key (id));
create table tax_types (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar2(255 char) not null, key varchar2(30 char) not null, percentage double precision not null, primary key (id));
create table triage (id number(19,0) not null, active_flag varchar2(1 char) not null, date_processed timestamp not null, date_row_added timestamp not null, email_body varchar2(2000 char), email_subject varchar2(500 char), email_to varchar2(200 char), include_attachment varchar2(1 char) not null, triage_notes varchar2(500 char), triage_action_id number(19,0), user_id number(19,0), primary key (id));
create table triage_action (id number(19,0) not null, action varchar2(255 char), active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, primary key (id));
create table unspsc_codes_lkup (id number(19,0) not null, active_flag varchar2(1 char) not null, code varchar2(50 char), date_row_added timestamp not null, date_row_updated timestamp not null, key varchar2(50 char), parent_key varchar2(50 char), title varchar2(255 char), title_msg_key varchar2(255 char), primary key (id));
create table uom_lookup (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, label varchar2(50 char), label_descr_msg_key varchar2(50 char), primary key (id));
create table user_auth (auth_name varchar2(50 char) not null, user_id number(19,0) not null, active_flag varchar2(1 char) not null, can_delete varchar2(1 char), can_read varchar2(1 char), can_write varchar2(1 char), date_row_added timestamp not null, date_row_updated timestamp not null, primary key (auth_name, user_id));
create table users (id number(19,0) not null, active_flag varchar2(1 char) not null, date_row_added timestamp not null, date_row_updated timestamp not null, first_name varchar2(50 char) not null, last_name varchar2(50 char) not null, password varchar2(50 char) not null, user_name varchar2(50 char) not null, primary key (id));
alter table user_auth add constraint UK_dmu723ru3iqigkd6q2nh6p1xf unique (auth_name);
alter table user_auth add constraint UK_nd1cbjapgbp1cohkrlhq2jky4 unique (user_id);
alter table audit_trail add constraint FK_AUDIT_TRAIL_FAIL_CODE_ID foreign key (fail_code_id) references fail_code;
alter table catalog add constraint FK_CATALOG_COMPANY_ID foreign key (company_id) references company;
alter table catalog add constraint FK_CATALOG_ORG_ID foreign key (organisation_id) references organisation;
alter table catalog add constraint FK_CATALOG_ID foreign key (parent_catalog_id) references catalog;
alter table catalog_child_item add constraint FK_CATALOG_ITEM_CHILD_ID foreign key (catalog_item_id) references catalog_item;
alter table catalog_child_item add constraint FK_CATALOG_CHILD_ID foreign key (catalog_id) references catalog;
alter table catalog_item add constraint FK_CATALOG_ITEM_ITEM_ID foreign key (item_id) references item;
alter table catalog_item add constraint FK_CATALOG_ITEM_SUBSTITUTE_ITEM_ID foreign key (substitute_item_id) references substitute_item;
alter table catalog_item_attribute add constraint FK_CATALOG_ITEM_ID foreign key (catalog_item_id) references catalog_item;
alter table catalog_item_price add constraint FK_CATALOG_ITEM_PRICE_ID foreign key (catalog_item_id) references catalog_item;
alter table company add constraint FK_COMPANY_ADDRESS_ID foreign key (address_id) references company_address;
alter table company add constraint FK_COMPANY_SIC_CODE_ID foreign key (sic_code_id) references sic_codes_lkup;
alter table company_change_log add constraint FK_COMPANY_CHANGE_LOG_COMPANY_ID foreign key (company_id) references company;
alter table company_change_log add constraint FK_COMPANY_CHANGE_LOG_IMPORT_ID foreign key (import_id) references import_transactions;
alter table gtin add constraint FK_GTIN_IMPORT_TRANSACTION_ID foreign key (import_transaction_id) references import_transactions;
alter table hibc add constraint FK_HIBC_IMPORT_TRANSACTION_ID foreign key (import_transaction_id) references import_transactions;
alter table item_asset add constraint FK_ITEM_ASSET_ITEM_ID foreign key (item_id) references item;
alter table item_attribute add constraint FK_ITEM_ATTRIBUTE_ITEM_ID foreign key (item_id) references item;
alter table item_barcode add constraint FK_ITEM_BARCODE_ITEM_ID foreign key (item_id) references item;
alter table item_barcode add constraint FKjw9xt7rgd1qn40ikglty8c253 foreign key (parent_item_barcode_id) references item_barcode;
alter table item_change_log add constraint FK_ITEM_CHANGE_LOG_ITEM_ID foreign key (item_id) references item;
alter table item_taxonomy add constraint FK_ITEM_TAXONOMY_BARCODE_ITEM_ID foreign key (item_id) references item;
alter table triage add constraint FK_TRIAGE_TRIAGE_ACTION_ID foreign key (triage_action_id) references triage_action;
alter table triage add constraint FK_TRIAGE_USER_ID foreign key (user_id) references users;
alter table user_auth add constraint FK_USER_AUTH_AUTH_NAME foreign key (auth_name) references auth;
alter table user_auth add constraint FK_USER_AUTH_USER_ID foreign key (user_id) references users;
