create sequence audit_trail_seq start 1 increment 1;
create sequence catalog_item_attribute_seq start 1 increment 1;
create sequence catalog_item_price_seq start 1 increment 1;
create sequence catalog_item_seq start 1 increment 1;
create sequence catalog_seq start 1 increment 1;
create sequence company_address_id_seq start 1 increment 1;
create sequence company_change_log_seq start 1 increment 1;
create sequence company_seq start 1 increment 1;
create sequence eclass_code_lkup_id_seq start 1 increment 1;
create sequence eclass_map_lkup_id_seq start 1 increment 1;
create sequence fail_code_seq start 1 increment 1;
create sequence gtin_id_seq start 1 increment 1;
create sequence hibc_id_seq start 1 increment 1;
create sequence import_transaction_id_seq start 1 increment 1;
create sequence item_asset_seq start 1 increment 1;
create sequence item_attribute_seq start 1 increment 1;
create sequence item_barcode_seq start 1 increment 1;
create sequence item_change_log_seq start 1 increment 1;
create sequence item_seq start 1 increment 1;
create sequence item_taxonomy_seq start 1 increment 1;
create sequence organisation_seq start 1 increment 1;
create sequence sic_code_seq start 1 increment 1;
create sequence substitute_item_seq start 1 increment 1;
create sequence tax_types_seq start 1 increment 1;
create sequence triage_action_seq start 1 increment 1;
create sequence triage_seq start 1 increment 1;
create sequence unspsc_code_seq start 1 increment 1;
create sequence uom_lookup_seq start 1 increment 1;
create sequence user_seq start 1 increment 1;
create table audit_trail (id int8 not null, comments varchar(255), date_row_added timestamp not null, display_text varchar(4000), document_no varchar(255) not null, status_addtl_info varchar(100), status_id int8 not null, fail_code_id int8, primary key (id));
create table auth (auth_name varchar(50) not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, primary key (auth_name));
create table catalog (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar(255), key varchar(50), name varchar(50), site varchar(50), type varchar(10), version int4, company_id int8, organisation_id int8, parent_catalog_id int8, primary key (id));
create table catalog_child_item (catalog_id int8 not null, catalog_item_id int8 not null, primary key (catalog_id, catalog_item_id));
create table catalog_item (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar(255), expense_code varchar(10) not null, hcted varchar(10) not null, item_band varchar(10), name varchar(50), pending_from varchar(10) not null, preferred_item_order varchar(10), supplier_part_no varchar(100), type varchar(10), uom_qty int8, validated varchar(1) not null, item_id int8, substitute_item_id int8, primary key (id));
create table catalog_item_attribute (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, key varchar(50), value varchar(255), catalog_item_id int8, primary key (id));
create table catalog_item_price (id int8 not null, active_flag varchar(1) not null, currency varchar(3), date_row_added timestamp not null, date_row_updated timestamp not null, lead_time varchar(50), net_amount numeric(10, 4) not null, max_order_qty int4, min_order_qty int4, price_break_max_qty int4, price_break_min_qty int4, price_break_style int4, price_type varchar(16), tax varchar(50), valid_from timestamp, valid_to timestamp, catalog_item_id int8, primary key (id));
create table company (id int8 not null, active_flag varchar(1) not null, companies_house_no varchar(100), company_key_1 varchar(100), company_key_2 varchar(100), company_name varchar(100), date_row_added timestamp not null, date_row_updated timestamp not null, duns_no varchar(100), nuts_code varchar(10), refresh varchar(1) not null, status varchar(20), sic_code_id int8, primary key (id));
create table company_address (id int8 not null, active_flag varchar(1) not null, address_name varchar(50) not null, city varchar(255), country_code varchar(10), date_row_added timestamp not null, date_row_updated timestamp not null, gln varchar(15) not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), nuts_code varchar(10), postal_code varchar(10), company_id int8, primary key (id));
create table company_change_log (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, information varchar(500), type varchar(10), company_id int8, import_id int8, primary key (id));
create table eclass_codes_lkup (eclass_code_lkup_id int8 not null, active_flag varchar(1) not null, code varchar(10), date_row_added timestamp not null, date_row_updated timestamp not null, description varchar(255), description_msg_key varchar(255), primary key (eclass_code_lkup_id));
create table eclass_mapping (id int8 not null, eclass_code varchar(3), eclass_description varchar(512), comments varchar(64), nca_code varchar(4), nca_description varchar(64), tfr_code varchar(3), tfr_description varchar(64), unspsc_code varchar(8), unspcs_description varchar(128), primary key (id));
create table fail_code (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar(50), name varchar(50), text varchar(100), primary key (id));
create table gtin (id int8 not null, active_flag varchar(1) not null, barcode_validation_id int8, date_row_added timestamp not null, date_row_updated timestamp not null, gtin int8 not null, text varchar(14) not null, type varchar(50) not null, import_transaction_id int8, primary key (id));
create table hibc (id int8 not null, active_flag varchar(1) not null, barcode_validation_id int8, date_row_added timestamp not null, date_row_updated timestamp not null, hibc varchar(50) not null, import_transaction_id int8, primary key (id));
create table import_transactions (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar(500), primary key (id));
create table item (id int8 not null, active_flag varchar(1) not null, brand varchar(128), date_row_added timestamp not null, date_row_updated timestamp not null, description varchar(255), gs1_gpc_code int8, long_description varchar(500), msrp float4, name varchar(100), replacement_mfgr_no varchar(100), synonyms varchar(500), type varchar(10), uom varchar(10), company_id int8, primary key (id));
create table item_asset (id int8 not null, active_flag varchar(1) not null, type varchar(10), date_row_added timestamp not null, date_row_updated timestamp not null, resource_location varchar(500), item_id int8, primary key (id));
create table item_attribute (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, key varchar(50), type varchar(10), value varchar(255), item_id int8, primary key (id));
create table item_barcode (id int8 not null, active_flag varchar(1) not null, code varchar(20), code_int int8, code_string varchar(10), date_row_added timestamp not null, date_row_updated timestamp not null, type varchar(10), item_id int8 not null, parent_item_barcode_id int8, primary key (id));
create table item_change_log (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, information varchar(500), type varchar(10), item_id int8, primary key (id));
create table item_taxonomy (id int8 not null, active_flag varchar(1) not null, code varchar(32), date_row_added timestamp not null, date_row_updated timestamp not null, taxonomy_type varchar(32), item_id int8 not null, primary key (id));
create table organisation (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, name varchar(64) not null, primary key (id));
create table sic_code (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar(255), section varchar(1), section_description varchar(128), sic_code varchar(50), primary key (id));
create table substitute_item (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, supplier_part_no varchar(50), primary key (id));
create table tax_types (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, description varchar(255) not null, key varchar(30) not null, percentage float8 not null, primary key (id));
create table triage (id int8 not null, active_flag varchar(1) not null, date_processed timestamp not null, date_row_added timestamp not null, email_body varchar(2000), email_subject varchar(500), email_to varchar(200), include_attachment varchar(1) not null, triage_notes varchar(500), triage_action_id int8, user_id int8, primary key (id));
create table triage_action (id int8 not null, action varchar(255), active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, primary key (id));
create table unspsc_code (id int8 not null, active_flag varchar(1) not null, code varchar(8), date_row_added timestamp not null, date_row_updated timestamp not null, title varchar(255), type varchar(16), parent_unspsc_code_id int8, primary key (id));
create table uom_lookup (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, label varchar(50), label_descr_msg_key varchar(50), primary key (id));
create table user_auth (id int8 not null, active_flag varchar(1) not null, can_delete varchar(1), can_read varchar(1), can_write varchar(1), date_row_added timestamp not null, date_row_updated timestamp not null, auth_name varchar(50) not null, user_id int8 not null, primary key (id));
create table users (id int8 not null, active_flag varchar(1) not null, date_row_added timestamp not null, date_row_updated timestamp not null, first_name varchar(50) not null, last_name varchar(50) not null, password varchar(50) not null, user_name varchar(50) not null, primary key (id));
alter table audit_trail add constraint FK_AUDIT_TRAIL_FAIL_CODE_ID foreign key (fail_code_id) references fail_code;
alter table catalog add constraint FK_CATALOG_COMPANY_ID foreign key (company_id) references company;
alter table catalog add constraint FK_CATALOG_ORG_ID foreign key (organisation_id) references organisation;
alter table catalog add constraint FK_CATALOG_ID foreign key (parent_catalog_id) references catalog;
alter table catalog_child_item add constraint FK_CATALOG_ITEM_CHILD_ID foreign key (catalog_item_id) references catalog_item;
alter table catalog_child_item add constraint FK_CATALOG_CHILD_ID foreign key (catalog_id) references catalog;
alter table catalog_item add constraint FK_CATALOG_ITEM_ITEM_ID foreign key (item_id) references item;
alter table catalog_item add constraint FK_CATALOG_ITEM_SUBSTITUTE_ITEM_ID foreign key (substitute_item_id) references substitute_item;
alter table catalog_item_attribute add constraint FK_CATALOG_ITEM_ID foreign key (catalog_item_id) references catalog_item;
alter table catalog_item_price add constraint FK_CATALOG_ITEM_PRICE_ID foreign key (catalog_item_id) references catalog_item;
alter table company add constraint FK_COMPANY_SIC_CODE_ID foreign key (sic_code_id) references sic_code;
alter table company_address add constraint FK_COMPANY_ADDRESS_COMPANY_ID foreign key (company_id) references company;
alter table company_change_log add constraint FK_COMPANY_CHANGE_LOG_COMPANY_ID foreign key (company_id) references company;
alter table company_change_log add constraint FK_COMPANY_CHANGE_LOG_IMPORT_ID foreign key (import_id) references import_transactions;
alter table gtin add constraint FK_GTIN_IMPORT_TRANSACTION_ID foreign key (import_transaction_id) references import_transactions;
alter table hibc add constraint FK_HIBC_IMPORT_TRANSACTION_ID foreign key (import_transaction_id) references import_transactions;
alter table item add constraint FK_ITEM_COMPANY_ID foreign key (company_id) references company;
alter table item_asset add constraint FK_ITEM_ASSET_ITEM_ID foreign key (item_id) references item;
alter table item_attribute add constraint FK_ITEM_ATTRIBUTE_ITEM_ID foreign key (item_id) references item;
alter table item_barcode add constraint FK_ITEM_BARCODE_ITEM_ID foreign key (item_id) references item;
alter table item_barcode add constraint FKjw9xt7rgd1qn40ikglty8c253 foreign key (parent_item_barcode_id) references item_barcode;
alter table item_change_log add constraint FK_ITEM_CHANGE_LOG_ITEM_ID foreign key (item_id) references item;
alter table item_taxonomy add constraint FK_ITEM_TAXONOMY_ITEM_ID foreign key (item_id) references item;
alter table triage add constraint FK_TRIAGE_TRIAGE_ACTION_ID foreign key (triage_action_id) references triage_action;
alter table triage add constraint FK_TRIAGE_USER_ID foreign key (user_id) references users;
alter table unspsc_code add constraint FKetawm5epvmefixdr6jeht2gyj foreign key (parent_unspsc_code_id) references unspsc_code;
alter table user_auth add constraint FK_USER_AUTH_AUTH_NAME foreign key (auth_name) references auth;
alter table user_auth add constraint FK_USER_AUTH_USER_ID foreign key (user_id) references users;
