CREATE TABLE USERS 
  (
    ID				NUMBER (10) NOT NULL,
    USER_NAME			VARCHAR2 (50 CHAR) NOT NULL,
    PASSWORD			VARCHAR2 (50 CHAR) NOT NULL,
    FIRST_NAME			VARCHAR2 (50 CHAR) NOT NULL,
    LAST_NAME			VARCHAR2 (50 CHAR) NOT NULL,
    DATE_ROW_ADDED      DATE NOT NULL,
    DATE_ROW_UPDATED    DATE NOT NULL,
    ACTIVE_FLAG         CHAR (1 CHAR) NOT NULL
  );
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY ( ID );
 
CREATE TABLE AUTH 
  (
    AUTH_NAME			VARCHAR2 (50 CHAR) NOT NULL,
    DATE_ROW_ADDED      DATE NOT NULL,
    DATE_ROW_UPDATED    DATE NOT NULL,
    ACTIVE_FLAG         CHAR (1 CHAR) NOT NULL
  );
ALTER TABLE AUTH ADD CONSTRAINT PK_AUTH PRIMARY KEY ( AUTH_NAME );

CREATE TABLE USER_AUTH 
  (
    USER_ID				NUMBER (10) NOT NULL,
    AUTH_NAME			VARCHAR2 (50 CHAR) NOT NULL,
    CAN_READ			CHAR (1 CHAR),
    CAN_WRITE			CHAR (1 CHAR),
    CAN_DELETE			CHAR (1 CHAR),
    DATE_ROW_ADDED      DATE NOT NULL,
    DATE_ROW_UPDATED    DATE NOT NULL,
    ACTIVE_FLAG         CHAR (1 CHAR) NOT NULL
  );
ALTER TABLE USER_AUTH ADD CONSTRAINT PK_USERS_AUTH PRIMARY KEY ( USER_ID,AUTH_NAME );
ALTER TABLE USER_AUTH ADD CONSTRAINT FK_USERS FOREIGN KEY ( USER_ID ) REFERENCES USERS ( ID ) NOT DEFERRABLE;
ALTER TABLE USER_AUTH ADD CONSTRAINT FK_AUTH FOREIGN KEY ( AUTH_NAME ) REFERENCES AUTH ( AUTH_NAME ) NOT DEFERRABLE;  

CREATE TABLE TRIAGE_ACTION
  (
    ID    NUMBER (10) NOT NULL,
    ACTION		VARCHAR2 (32 CHAR),
    DATE_ROW_ADDED      DATE NOT NULL,
    DATE_ROW_UPDATED	DATE NOT NULL,
    ACTIVE_FLAG         CHAR (1 CHAR) NOT NULL
  );
ALTER TABLE TRIAGE_ACTION ADD CONSTRAINT PK_TRIAGE_ACTION PRIMARY KEY ( ID );
CREATE SEQUENCE TRIAGE_ACTION_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE TRIAGE
  (
    ID             		  NUMBER (10) NOT NULL,
    TRIAGE_ACTION_ID	  NUMBER (10) NOT NULL,
    USER_ID				  NUMBER (10) NOT NULL,
    TRIAGE_NOTES		  VARCHAR2 (255 CHAR),
    EMAIL_TO			  VARCHAR2 (255 CHAR),
    EMAIL_SUBJECT		  VARCHAR2 (64 CHAR),
    EMAIL_BODY			  VARCHAR2 (4000 CHAR),
    DATE_ROW_ADDED        DATE NOT NULL,
    DATE_PROCESSED        DATE,
    ACTIVE_FLAG           CHAR (1 CHAR) NOT NULL,
	INCLUDE_ATTACHMENT 	  CHAR (1 CHAR) NOT NULL
  );
CREATE SEQUENCE TRIAGE_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE TRIAGE ADD CONSTRAINT PK_TRIAGE PRIMARY KEY ( ID );
ALTER TABLE TRIAGE ADD CONSTRAINT FK_TRIAGE_ACTION FOREIGN KEY ( TRIAGE_ACTION_ID ) REFERENCES TRIAGE_ACTION ( ID ) NOT DEFERRABLE;
ALTER TABLE TRIAGE ADD CONSTRAINT FK_USER FOREIGN KEY ( USER_ID ) REFERENCES USERS ( ID ) NOT DEFERRABLE;

CREATE TABLE TAX_TYPES
  (
    ID						NUMBER(10) NOT NULL,
    KEY						VARCHAR2(30 CHAR) NOT NULL,
    DESCRIPTION		  		VARCHAR2(255 CHAR),
    PERCENTAGE				NUMBER(10,4) NOT NULL,
    ACTIVE_FLAG           	CHAR (1 CHAR) NOT NULL,
    DATE_ROW_ADDED        	DATE NOT NULL,
    DATE_ROW_UPDATED       	DATE NOT NULL
  );
CREATE SEQUENCE TAX_TYPES_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE TAX_TYPES ADD CONSTRAINT PK_TAX_TYPES PRIMARY KEY(ID);


CREATE TABLE FAIL_CODE
  (
    ID						NUMBER (10) NOT NULL,
    NAME         			VARCHAR2 (50 CHAR),
    DESCRIPTION 			VARCHAR2 (255 CHAR),
    DATE_ROW_ADDED          DATE NOT NULL,
    DATE_ROW_UPDATED        DATE NOT NULL,
    ACTIVE_FLAG             CHAR (1 CHAR) NOT NULL,
	TEXT			 		VARCHAR2(100 CHAR)
  );
CREATE SEQUENCE FAIL_CODE_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE FAIL_CODE ADD CONSTRAINT PK_FAIL_CODE PRIMARY KEY ( ID );

CREATE TABLE AUDIT_TRAIL
  (
	ID				        NUMBER (10) NOT NULL,
    DOCUMENT_NO				VARCHAR2 (100 CHAR),
    STATUS_ID          	    NUMBER (10) NOT NULL,
    DATE_ROW_ADDED          DATE NOT NULL,
    STATUS_ADDTL_INFO       VARCHAR2 (100 CHAR),
    DISPLAY_TEXT            VARCHAR2 (4000 CHAR),
    COMMENTS                VARCHAR2 (255 CHAR),
    FAIL_CODE_ID            NUMBER (10)
  );
CREATE SEQUENCE AUDIT_TRAIL_SEQ START WITH 1 INCREMENT BY 1; 
ALTER TABLE AUDIT_TRAIL ADD CONSTRAINT PK_AUDIT_TRAIL PRIMARY KEY (ID);
ALTER TABLE AUDIT_TRAIL ADD CONSTRAINT FK_AUDIT_TRAIL_FAIL_CODE FOREIGN KEY ( FAIL_CODE_ID ) REFERENCES FAIL_CODE ( ID ) NOT DEFERRABLE;

CREATE TABLE UOM_LOOKUP
  (
    ID           	    			NUMBER (10) NOT NULL,
    LABEL         	    			VARCHAR2 (50 CHAR),
    LABEL_DESCR_MSG_KEY 	    	VARCHAR2 (100 CHAR),
    DATE_ROW_ADDED                  DATE NOT NULL,
    DATE_ROW_UPDATED                DATE NOT NULL,
    ACTIVE_FLAG                     CHAR (1 CHAR) NOT NULL
  );
CREATE SEQUENCE UOM_LOOKUP_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE UOM_LOOKUP ADD CONSTRAINT PK_UOM_LOOKUP PRIMARY KEY ( ID );

CREATE TABLE SIC_CODES_LKUP 
  (
    ID						NUMBER (10) NOT NULL,
    SIC_CODE				VARCHAR2 (50 CHAR) NOT NULL,
    DESCRIPTION				VARCHAR2 (255 CHAR) NOT NULL,
    DESCRIPTION_MSG_KEY		VARCHAR2 (255 CHAR) NOT NULL,
    DATE_ROW_ADDED      	DATE NOT NULL,
    DATE_ROW_UPDATED    	DATE NOT NULL,
    ACTIVE_FLAG         	CHAR (1 CHAR) NOT NULL
  );
CREATE SEQUENCE SIC_CODE_LKUP_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE SIC_CODES_LKUP ADD CONSTRAINT PK_SIC_CODES_LKUP PRIMARY KEY ( ID );

CREATE TABLE UNSPSC_CODES_LKUP 
  (
    ID						NUMBER (10) NOT NULL,
    KEY						VARCHAR2 (50 CHAR) NOT NULL,
    PARENT_KEY				VARCHAR2 (50 CHAR) ,
    CODE					VARCHAR2 (50 CHAR) NOT NULL,
    TITLE					VARCHAR2 (255 CHAR) NOT NULL,
    TITLE_MSG_KEY			VARCHAR2 (255 CHAR) NOT NULL,
    DATE_ROW_ADDED      	DATE NOT NULL,
    DATE_ROW_UPDATED    	DATE NOT NULL,
    ACTIVE_FLAG         	CHAR (1 CHAR) NOT NULL
  );
CREATE SEQUENCE UNSPSC_CODE_LKUP_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE UNSPSC_CODES_LKUP ADD CONSTRAINT PK_UNSPSC_CODES_LKUP PRIMARY KEY ( ID );

CREATE TABLE ECLASS_CODES_LKUP 
  (
    ID						NUMBER (10) NOT NULL,
    CODE					VARCHAR2 (5 CHAR) NOT NULL,
    DESCRIPTION				VARCHAR2 (255 CHAR) NOT NULL,
    DESCRIPTION_MSG_KEY		VARCHAR2 (255 CHAR) NOT NULL,
    DATE_ROW_ADDED      	DATE NOT NULL,
    DATE_ROW_UPDATED    	DATE NOT NULL,
    ACTIVE_FLAG         	CHAR (1 CHAR) NOT NULL
  );
CREATE SEQUENCE ECLASS_CODE_LKUP_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE ECLASS_CODES_LKUP ADD CONSTRAINT PK_ECLASS_CODES_LKUP PRIMARY KEY ( ID );

CREATE TABLE IMPORT_TRANSACTIONS 
  (
    ID						NUMBER (10) NOT NULL,
    DESCRIPTION				VARCHAR2 (500 CHAR), 
    DATE_ROW_ADDED      	DATE NOT NULL,
    DATE_ROW_UPDATED    	DATE NOT NULL,
    ACTIVE_FLAG         	CHAR (1 CHAR) NOT NULL
  );
CREATE SEQUENCE IMPORT_TRANSACTION_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE IMPORT_TRANSACTIONS ADD CONSTRAINT PK_IMPORT_TRANSACTIONS PRIMARY KEY ( ID );

CREATE TABLE GTIN 
  (
    ID						NUMBER (10) NOT NULL,
    GTIN					NUMBER (10) NOT NULL,
    GTIN_TEXT				VARCHAR2 (14 CHAR) NOT NULL,
    GTIN_TYPE				VARCHAR2 (50 CHAR) NOT NULL,
    IMPORT_TRANSACTION_ID	NUMBER (10),
    BARCODE_VALIDATION_ID	NUMBER (10),
    DATE_ROW_ADDED      	DATE NOT NULL,
    DATE_ROW_UPDATED    	DATE NOT NULL,
    ACTIVE_FLAG         	CHAR (1 CHAR) NOT NULL
  );
CREATE SEQUENCE GTIN_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE GTIN ADD CONSTRAINT PK_GTIN PRIMARY KEY ( ID );
ALTER TABLE GTIN ADD CONSTRAINT FK_GTIN_IMPORT_TRANSACTION_ID FOREIGN KEY ( IMPORT_TRANSACTION_ID ) REFERENCES IMPORT_TRANSACTIONS ( ID ) NOT DEFERRABLE;

CREATE TABLE HIBC 
  (
    ID						NUMBER (10) NOT NULL,
    HIBC					VARCHAR2 (50 CHAR) NOT NULL,
    IMPORT_TRANSACTION_ID	NUMBER (10),
    BARCODE_VALIDATION_ID	NUMBER (10),
    DATE_ROW_ADDED      	DATE NOT NULL,
    DATE_ROW_UPDATED    	DATE NOT NULL,
    ACTIVE_FLAG         	CHAR (1 CHAR) NOT NULL
  );
CREATE SEQUENCE HIBC_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE HIBC ADD CONSTRAINT PK_HIBC PRIMARY KEY ( ID );
ALTER TABLE HIBC ADD CONSTRAINT FK_HIBC_IMPORT_TRANSACTION_ID FOREIGN KEY ( IMPORT_TRANSACTION_ID ) REFERENCES IMPORT_TRANSACTIONS ( ID ) NOT DEFERRABLE;


/