DROP TABLE USERS;
DROP TABLE AUTH;
DROP TABLE USER_AUTH;
DROP TABLE TRIAGE_ACTION;
DROP TABLE TRIAGE;
DROP TABLE TAX_TYPES;
DROP TABLE FAIL_CODE;
DROP TABLE AUDIT_TRAIL;
DROP TABLE UOM_LOOKUP;
DROP TABLE GTIN;
DROP TABLE HIBC;
DROP TABLE IMPORT_TRANSACTIONS;



DROP SEQUENCE USER_SEQ;
DROP SEQUENCE TRIAGE_ACTION_SEQ;
DROP SEQUENCE TRIAGE_SEQ;
DROP SEQUENCE TAX_TYPES_SEQ;
DROP SEQUENCE FAIL_CODE_SEQ;
DROP SEQUENCE AUDIT_TRAIL_SEQ; 
DROP SEQUENCE UOM_LOOKUP_SEQ;
DROP SEQUENCE GTIN_SEQ;
DROP SEQUENCE HIBC_SEQ;
DROP SEQUENCE IMPORT_TRANSACTION_SEQ;


/